sudo: false
language: c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - valgrind
      - cppcheck
      - gcovr
install:
  - "[ $GCC = gcc ] && export GCC=gcc || true"
script:
  - cd examples
  - cd identifier
  - make clean compile UnitTests
  - make clean compile valgrind
  - make clean cov
